# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2015-04-05 14:32+0200\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=CHARSET\n"
"Content-Transfer-Encoding: 8bit\n"

#: ../tracer/controllers/default.py:84
msgid "Press application number for help or 'q' to quit"
msgstr ""

#: ../tracer/controllers/default.py:92
msgid "Wrong application number"
msgstr ""

#: ../tracer/controllers/default.py:94
msgid "Press <enter> to get list of applications"
msgstr ""

#: ../tracer/controllers/helper.py:55
msgid "You don't have enough permissions"
msgstr ""

#: ../tracer/controllers/helper.py:65
#, python-brace-format
msgid "Application called {0} is not running"
msgstr ""

#: ../tracer/resources/applications.py:112
msgid "You will have to reboot your computer"
msgstr ""

#: ../tracer/resources/applications.py:115
msgid "You will have to log out & log in again"
msgstr ""

#: ../tracer/resources/router.py:46
msgid "Only root can use this application"
msgstr ""

#: ../tracer/resources/exceptions.py:30
#, python-brace-format
msgid ""
"You are running unsupported linux distribution\n"
"\n"
"Please visit https://github.com/FrostyX/tracer/issues\n"
"and create new issue called 'Unknown or unsupported linux distribution: {0} "
"(v{1})' if there isn't such.\n"
"\n"
"Don't you have an GitHub account? Please report this issue on frostyx@email."
"cz"
msgstr ""

#: ../tracer/resources/exceptions.py:45
msgid "Package database is locked by another process"
msgstr ""

#: ../tracer/resources/exceptions.py:55
msgid "You can't open package database due to insufficient permissions"
msgstr ""

#: ../tracer/resources/exceptions.py:66
#, python-brace-format
msgid ""
"Problem occurred - neither one of {0} paths exists\n"
"Please contact maintainer of tracer package in your distribution."
msgstr ""

#: ../tracer/views/interactive.py:11 ../tracer/views/default.py:70
msgid "You should restart:"
msgstr ""

#: ../tracer/views/default.py:51
msgid "Some applications using:"
msgstr ""

#: ../tracer/views/default.py:52
msgid "These applications manually:"
msgstr ""

#: ../tracer/views/default.py:57
msgid "These applications restarting your session:"
msgstr ""

#: ../tracer/views/default.py:61
msgid "These applications rebooting your computer:"
msgstr ""

#: ../tracer/views/helper.py:46
msgid "How to restart"
msgstr ""

#: ../tracer/views/helper.py:57
msgid "Affected by"
msgstr ""

#: ../tracer/views/note_for_hidden.py:13
msgid "There are:"
msgstr ""

#: ../tracer/views/note_for_hidden.py:15
msgid "Additionally to those process above, there are:"
msgstr ""

#: ../tracer/views/note_for_hidden.py:19
#, python-brace-format
msgid ""
"{0} processes requiring restart of your session (i.e. Logging out & Logging "
"in again)"
msgstr ""

#: ../tracer/views/note_for_hidden.py:25
#, python-brace-format
msgid "{0} processes requiring reboot"
msgstr ""
